-- 0001_init.up.sql
-- Domínio financeiro: carteira, ledger imutável, transações de aposta,
-- outbox (publicação durável) e inbox (idempotência do consumidor SQS).
-- O schema abaixo espelha exatamente as consultas dos repositórios da camada
-- internal/storage/postgres.

BEGIN;

-- ---------------------------------------------------------------------------
-- Carteiras
-- ---------------------------------------------------------------------------
CREATE TABLE wallets (
    id            TEXT        PRIMARY KEY,
    provider_id   TEXT        NOT NULL,
    player_id     TEXT        NOT NULL,
    currency      CHAR(3)     NOT NULL,
    balance_units BIGINT      NOT NULL DEFAULT 0,
    version       BIGINT      NOT NULL DEFAULT 0,
    status        TEXT        NOT NULL DEFAULT 'ACTIVE',
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT wallets_balance_nonnegative CHECK (balance_units >= 0),
    -- Uma carteira pertence a um provedor+player+moeda (isolamento por provedor)
    CONSTRAINT wallets_unique_provider_player_currency
        UNIQUE (provider_id, player_id, currency)
);

CREATE INDEX idx_wallets_player ON wallets (player_id);
CREATE INDEX idx_wallets_provider ON wallets (provider_id);

-- ---------------------------------------------------------------------------
-- Ledger imutável (append-only)
-- ---------------------------------------------------------------------------
-- Cada linha é um lançamento financeiro. NUNCA é atualizada nem removida:
-- balance_before/after garantem continuidade e seq dá ordem estável (cursor).
CREATE TABLE wallet_ledger (
    id             TEXT        PRIMARY KEY,
    wallet_id      TEXT        NOT NULL REFERENCES wallets (id),
    transaction_id TEXT        NOT NULL,
    direction      TEXT        NOT NULL,
    amount_units   BIGINT      NOT NULL,
    balance_before BIGINT      NOT NULL,
    balance_after  BIGINT      NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    seq            BIGINT      GENERATED BY DEFAULT AS IDENTITY,

    -- Imutabilidade: cada operação financeira produz no máximo um lançamento.
    CONSTRAINT ledger_tx_unique UNIQUE (wallet_id, transaction_id),

    CONSTRAINT ledger_balance_match
        CHECK (balance_after = balance_before + CASE WHEN direction = 'CREDIT' THEN amount_units ELSE -amount_units END),
    CONSTRAINT ledger_amount_positive CHECK (amount_units >= 0),
    CONSTRAINT ledger_direction_valid CHECK (direction IN ('DEBIT', 'CREDIT'))
);

CREATE INDEX idx_ledger_wallet_seq ON wallet_ledger (wallet_id, seq);

-- Imutabilidade do ledger: nenhum processo pode atualizar nem remover
-- lançamentos. Correções requerem novas entradas (estornadas), nunca UPDATE.
CREATE FUNCTION prevent_ledger_modification() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'wallet_ledger is append-only';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER ledger_no_update_or_delete
    BEFORE UPDATE OR DELETE ON wallet_ledger
    FOR EACH ROW EXECUTE FUNCTION prevent_ledger_modification();

-- ---------------------------------------------------------------------------
-- Transações de aposta (máquina de estados persistida)
-- ---------------------------------------------------------------------------
CREATE TABLE wagering_transactions (
    id                    TEXT        PRIMARY KEY,
    provider_id           TEXT        NULL,
    player_id             TEXT        NOT NULL,
    wallet_id             TEXT        NOT NULL REFERENCES wallets (id),
    round_id              TEXT        NULL,
    game_id               TEXT        NULL,
    kind                  TEXT        NOT NULL,
    amount_units          BIGINT      NOT NULL DEFAULT 0,
    currency              CHAR(3)     NOT NULL,
    external_tx_id        TEXT        NULL,
    reference_ext_id      TEXT        NULL,
    reference_internal_id TEXT        NULL,
    idempotency_key       TEXT        NULL,
    correlation_id        TEXT        NULL,
    causation_id          TEXT        NULL,
    occurred_at           TIMESTAMPTZ NOT NULL,
    recorded_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    processed_at          TIMESTAMPTZ NULL,
    wallet_version        BIGINT      NOT NULL DEFAULT 0,
    failure_code          TEXT        NULL,
    failure_message       TEXT        NULL,
    payload_hash          TEXT        NULL,
    state                 TEXT        NOT NULL,
    attempts              INT         NOT NULL DEFAULT 0,
    next_attempt_at       TIMESTAMPTZ NULL,
    result_balance_units  BIGINT      NULL,

    -- Idempotência por provedor (replay não duplica); OPENING usa NULL em
    -- provider/external/key, mantidos distintos pela semântica de NULLs.
    CONSTRAINT wagering_idempotency_unique UNIQUE (provider_id, idempotency_key),
    -- Um external_tx_id do provedor só aparece uma vez.
    CONSTRAINT wagering_external_unique UNIQUE (provider_id, external_tx_id),
    CONSTRAINT wagering_kind_valid CHECK (kind IN ('BET','WIN','LOSS','REFUND','ROLLBACK','OPENING')),
    CONSTRAINT wagering_state_valid CHECK (state IN ('PENDING','PENDING_REFERENCE','PROCESSED','REJECTED','FAILED')),
    CONSTRAINT wagering_currency_valid CHECK (currency IN ('BRL'))
);

CREATE INDEX idx_wagering_wallet_state ON wagering_transactions (wallet_id, state);
CREATE INDEX idx_wagering_reference_ext ON wagering_transactions (reference_ext_id)
    WHERE reference_ext_id IS NOT NULL;

-- ---------------------------------------------------------------------------
-- Outbox (publicação durável, transação atômica com o evento de origem)
-- ---------------------------------------------------------------------------
CREATE TABLE outbox (
    id             TEXT        PRIMARY KEY,
    aggregate_type TEXT        NOT NULL,
    aggregate_id   TEXT        NOT NULL,
    event_type     TEXT        NOT NULL,
    payload        JSONB       NOT NULL,
    correlation_id TEXT        NULL,
    causation_id   TEXT        NULL,
    occurred_at    TIMESTAMPTZ NOT NULL,
    version        INT         NOT NULL DEFAULT 0,
    status         TEXT        NOT NULL DEFAULT 'PENDING',
    attempts       INT         NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    published_at   TIMESTAMPTZ NULL,
    published_by   TEXT        NULL,

    CONSTRAINT outbox_status_valid CHECK (status IN ('PENDING', 'PUBLISHED', 'DLQ'))
);

CREATE INDEX idx_outbox_pending ON outbox (status, next_attempt_at) WHERE status = 'PENDING';

-- ---------------------------------------------------------------------------
-- Inbox (idempotência durável do consumidor SQS por mensagem)
-- ---------------------------------------------------------------------------
CREATE TABLE inbox (
    consumer_name TEXT        NOT NULL,
    message_id    TEXT        NOT NULL,
    payload_hash  TEXT        NOT NULL,
    status        TEXT        NOT NULL DEFAULT 'RECEIVED',
    received_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    processed_at  TIMESTAMPTZ NULL,
    failure_code  TEXT        NULL,

    CONSTRAINT inbox_pk PRIMARY KEY (consumer_name, message_id),
    CONSTRAINT inbox_status_valid CHECK (status IN ('RECEIVED', 'PROCESSED', 'FAILED'))
);

-- ---------------------------------------------------------------------------
-- Meta de migrations (aplicada pela ferramenta de migração embutida)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS schema_version (
    version    INT          NOT NULL,
    applied_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    PRIMARY KEY (version)
);

COMMIT;